### ISSUE TITLE
"UNI" weight application

### ISSUE THREAD

**Issue by JAAY-AI** [ajv012/cpath_demographics#1]
Hello dear author, thank you very much for your work! I am very interested in your work, especially the "UNI" feature extractor you used in your research, its performance is so exciting, but I applied for it twice to the author of "UNI" on the "HuggingFace" website The permission to use the "UNI" weight has been denied, which makes me a little sad. How can I obtain the permission to use the "UNI" weight? Is it because the personal email address I used when I applied is not allowed to be used?

**Comment by ajv012** [comment]
This repository does not distribute UNI weights. Please refer to the readme in https://github.com/mahmoodlab/UNI to obtain the weights.
