### ISSUE TITLE
Incorporating Additional Factors into CPATH Prediction

### ISSUE THREAD

**Issue by tjwy** [ajv012/cpath_demographics#2]
Thank you for your outstanding work! I'd like to inquire, if factors beyond race, such as sex, age, and others, also influence the CPATH results, can these factors be considered as part of the predictive variables and be included in the training process? For instance, can they be integrated with WSI embeddings and included in the classifier for training?

**Comment by ajv012** [comment]
Thank you for your question. Factors other than race can be considered in the analysis and are provided at: https://github.com/mahmoodlab/CPATH_demographics/blob/main/splits_MonteCarlo/TCGA_GBMLGG/test.csv. We cannot provide any metadata about the private cohorts (i.e., those for breast and lung subtyping). Closing this issue, but feel free to open if any additional questions.
